/* VÉLISSE — content data.
   Edit these arrays to change products, collections, or journal posts.
   No build step required — this file is loaded directly by the browser. */

const VELISSE_COLLECTIONS = [
  {
    id: 'cantilever',
    name: 'Cantilever',
    tagline: 'Structure held in balance',
    description: 'A study in suspended weight — bands and settings that appear to defy gravity, echoing the cantilevered forms of modernist architecture.',
    motif: 'column',
    year: '2025',
  },
  {
    id: 'endgame',
    name: 'Endgame',
    tagline: 'Pieces of quiet strategy',
    description: "Sculptural rings and pendants drawn from the geometry of chess — every piece deliberate, every silhouette a position held.",
    motif: 'chess',
    year: '2025',
  },
  {
    id: 'gallery',
    name: 'The Gallery',
    tagline: "Wearable objets d'art",
    description: "Jewelry conceived as museum pieces first — plinths, frames, and negative space translated into gold and stone.",
    motif: 'gallery',
    year: '2024',
  },
  {
    id: 'monolith',
    name: 'Monolith',
    tagline: 'Mass, distilled',
    description: 'Solid, sculptural forms inspired by brutalist massing — heavy on the eye, weightless on the hand.',
    motif: 'sculpture',
    year: '2024',
  },
]

const VELISSE_PRODUCTS = [
  {
    id: 'meridian-ring',
    name: 'Meridian Ring',
    collection: 'cantilever',
    category: 'rings',
    price: 4200,
    currency: 'USD',
    materials: '18k yellow gold, cantilevered band',
    description: 'A single line of gold cantilevers off the finger, balanced by an unseen counterweight of mass on the interior band.',
    motif: 'column',
    featured: true,
  },
  {
    id: 'corbel-cuff',
    name: 'Corbel Cuff',
    collection: 'cantilever',
    category: 'bracelets',
    price: 6800,
    currency: 'USD',
    materials: '18k white gold, brushed finish',
    description: "Named for the architectural bracket, this cuff projects from the wrist in a single confident overhang.",
    motif: 'column',
    featured: false,
  },
  {
    id: 'knight-pendant',
    name: 'Knight Pendant',
    collection: 'endgame',
    category: 'necklaces',
    price: 3400,
    currency: 'USD',
    materials: '18k gold vermeil, black onyx base',
    description: "The knight's silhouette abstracted into two planes of gold, suspended on a fine box chain.",
    motif: 'chess',
    featured: true,
  },
  {
    id: 'castle-band',
    name: 'Castle Band',
    collection: 'endgame',
    category: 'rings',
    price: 2900,
    currency: 'USD',
    materials: '18k yellow gold, crenellated edge',
    description: 'A fortified silhouette worn low on the finger — strength read as ornament.',
    motif: 'chess',
    featured: false,
  },
  {
    id: 'plinth-earrings',
    name: 'Plinth Earrings',
    collection: 'gallery',
    category: 'earrings',
    price: 3100,
    currency: 'USD',
    materials: '18k gold, hand-set diamonds',
    description: 'Each earring rests on its own sculptural base, as if lit from below in a private gallery.',
    motif: 'gallery',
    featured: true,
  },
  {
    id: 'frame-necklace',
    name: 'Frame Necklace',
    collection: 'gallery',
    category: 'necklaces',
    price: 5200,
    currency: 'USD',
    materials: '18k gold, open rectilinear pendant',
    description: 'An empty frame at the throat — a deliberate space left for the wearer to complete.',
    motif: 'gallery',
    featured: false,
  },
  {
    id: 'monolith-signet',
    name: 'Monolith Signet',
    collection: 'monolith',
    category: 'rings',
    price: 3800,
    currency: 'USD',
    materials: '18k gold, high-polish slab face',
    description: 'A single unbroken plane of gold, cast heavy and left unornamented.',
    motif: 'sculpture',
    featured: true,
  },
  {
    id: 'massing-hoops',
    name: 'Massing Hoops',
    collection: 'monolith',
    category: 'earrings',
    price: 2600,
    currency: 'USD',
    materials: '18k gold, graduated thickness',
    description: "Hoops that thicken toward the base, distributing weight like a building's foundation.",
    motif: 'sculpture',
    featured: false,
  },
]

const VELISSE_JOURNAL = [
  {
    id: 'on-cantilevers',
    title: 'On Cantilevers, and the Jewelry That Refuses to Sit Still',
    excerpt: 'What Frank Lloyd Wright understood about suspended weight, and how it found its way into a ring.',
    date: '2026-06-02',
    category: 'Architecture',
    motif: 'column',
    body: [
      "A cantilever holds its weight without a visible means of support — the load travels backward, through mass you cannot see, into a foundation doing quiet work far from the point of drama.",
      "It is, we think, the most honest metaphor for jewelry we have found. A ring worn well doesn't announce its engineering; it simply holds, and the wearer forgets to wonder how.",
      'The Cantilever collection began with this single structural idea, sketched first as a section drawing, long before it was ever rendered in gold.',
    ],
  },
  {
    id: 'chess-as-form',
    title: 'Chess as Form: Designing the Endgame Collection',
    excerpt: 'Sixty-four squares, six pieces, infinite positions — a conversation with our design studio on translating strategy into gold.',
    date: '2026-04-18',
    category: 'Process',
    motif: 'chess',
    body: [
      'Chess pieces are among the oldest examples of pure abstraction in design history — a knight has never looked like a horse, and yet no one has ever mistaken it for anything else.',
      'That economy of form is what drew us to the board. Each piece in Endgame borrows a silhouette from the game, reduced further, until only the gesture remains.',
      'We were less interested in the pieces themselves than in what they represent: position, intention, and the specific quiet of a considered move.',
    ],
  },
  {
    id: 'the-plinth-problem',
    title: 'The Plinth Problem: Why We Design Jewelry Like Sculpture',
    excerpt: 'Every object needs a base. We started asking what happens when the body becomes one.',
    date: '2026-02-27',
    category: 'Philosophy',
    motif: 'gallery',
    body: [
      "In a gallery, a plinth exists to do one job: lift an object out of ordinary space and tell you, without words, that it deserves your attention.",
      "We began to wonder what it would mean to design jewelry with that same logic — pieces that don't merely sit on the body, but that treat the body as the plinth itself.",
      'The Gallery collection is our answer: settings and frames that borrow the language of museum display, built for a body in motion rather than a room at rest.',
    ],
  },
  {
    id: 'negative-space',
    title: 'In Praise of Negative Space',
    excerpt: 'The parts of a piece we choose to leave empty are doing as much work as the parts we fill.',
    date: '2025-11-14',
    category: 'Philosophy',
    motif: 'sculpture',
    body: [
      'It is tempting, in jewelry design, to fill every available surface — more stones, more metal, more evidence of the hours spent making the thing.',
      'We have found the opposite instinct more interesting. A gap left in a band, a frame with nothing set inside it, a hoop that thins to almost nothing before it thickens again.',
      "Negative space isn't a void. It's a decision, and often the hardest one a designer makes.",
    ],
  },
]
